# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  polyspace-static-analysis:
    # Self-hosted runner kullanıyoruz. Windows ise şu etiketleri verin:
    runs-on: [self-hosted, Windows]

    env:
      # Polyspace kurulumuna göre bu yolu özelleştirin (ör. R2025a/R2024b)
      POLYSPACE_BIN: "C:\\Program Files\\Polyspace\\R2024b\\polyspace\\bin"
      SRC_DIR: "src"
      RESULTS_DIR: "results\\bugfinder"
      REPORT_DIR: "results\\report"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify Polyspace CLI on PATH
        shell: pwsh
        run: |
          if (-not (Test-Path "$env:POLYSPACE_BIN")) {
            Write-Error "POLYSPACE_BIN not found at $env:POLYSPACE_BIN. Update the path in ci.yml."
          }
          $env:Path = "$env:POLYSPACE_BIN;$env:Path"
          Write-Host "polyspace-bug-finder version:"
          polyspace-bug-finder -version

      - name: Create results folders
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path "$env:RESULTS_DIR" | Out-Null
          New-Item -ItemType Directory -Force -Path "$env:REPORT_DIR" | Out-Null

      - name: Run Polyspace Bug Finder
        shell: pwsh
        run: |
          # Tek dosya örneği: src/whichQuadrant.c
          # Birden fazla dosya varsa *.c/*.h kalıbını genişletebilirsiniz.
          polyspace-bug-finder `
            -results-dir "$env:RESULTS_DIR" `
            -sources "$env:SRC_DIR\\whichQuadrant.c" `
            -lang c `
            -target msvc `
            -main-generator on `
            -prove-def false `
            -verbose-level 2

      - name: Generate HTML report
        shell: pwsh
        run: |
          polyspace-report-generator `
            -results-dir "$env:RESULTS_DIR" `
            -report-dir "$env:REPORT_DIR" `
            -format html `
            -include-sources on `
            -title "Polyspace Bug Finder Report"

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: polyspace-report
          path: results/report
          if-no-files-found: error

      # (Opsiyonel) Kalite kapısı: belirli şiddette bulgu varsa job'ı fail et
      # Eşikleri ortam değişkenleriyle yönetebilirsiniz.
      - name: Fail build if High/Medium findings exist (optional)
        if: always()
        shell: pwsh
        run: |
          # Basit bir kontrol: HTML raporda "High" veya "Medium" metni geçiyorsa fail et.
          $reportIndex = Join-Path "$env:REPORT_DIR" "index.html"
          if (-not (Test-Path $reportIndex)) {
            Write-Error "Report index not found: $reportIndex"
          }
          $html = Get-Content $reportIndex -Raw
          $hasHigh = $html -match "High"
          $hasMedium = $html -match "Medium"
          if ($hasHigh -or $hasMedium) {
            Write-Error "Polyspace findings exceed threshold (High/Medium)."
          } else {
            Write-Host "No High/Medium findings detected."
          }

  # --- Linux self-hosted alternatifi (yorumdan çıkarıp üst job'ı kapatabilirsiniz) ---
  # polyspace-static-analysis-linux:
  #   runs-on: [self-hosted, Linux]
  #   env:
  #     POLYSPACE_BIN: "/usr/local/Polyspace/R2024b/polyspace/bin"
  #     SRC_DIR: "src"
  #     RESULTS_DIR: "results/bugfinder"
  #     REPORT_DIR: "results/report"
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Verify Polyspace CLI on PATH
  #       run: |
  #         if [ ! -d "$POLYSPACE_BIN" ]; then
  #           echo "POLYSPACE_BIN not found at $POLYSPACE_BIN" >&2
  #           exit 1
  #         fi
  #         echo "$POLYSPACE_BIN" >> $GITHUB_PATH
  #         polyspace-bug-finder -version
  #     - name: Create results folders
  #       run: |
  #         mkdir -p "$RESULTS_DIR" "$REPORT_DIR"
  #     - name: Run Polyspace Bug Finder
  #       run: |
  #         polyspace-bug-finder \
  #           -results-dir "$RESULTS_DIR" \
  #           -sources "$SRC_DIR/whichQuadrant.c" \
  #           -lang c \
  #           -target gcc \
  #           -main-generator on \
  #           -prove-def false \
  #           -verbose-level 2
  #     - name: Generate HTML report
  #       run: |
  #         polyspace-report-generator \
  #           -results-dir "$RESULTS_DIR" \
  #           -report-dir "$REPORT_DIR" \
  #           -format html \
  #           -include-sources on \
  #           -title "Polyspace Bug Finder Report"
  #     - name: Upload report artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: polyspace-report
  #         path: results/report
  #         if-no-files-found: error
