# .github/workflows/ci-windows.yml
name: MATLAB CI on Self-Hosted Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  matlab-build:
    # Kendi self-hosted Windows runner'ınıza uygun etiketler
    runs-on: [ self-hosted, windows, x64 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run MATLAB buildfile
        shell: pwsh
        run: |
          # Eğer buildfile.m yerine başka bir .m dosyanız varsa ismini değiştirin
          matlab -batch "try, run('buildfile.m'); catch ME, disp(getReport(ME,'extended')); exit(1); end; exit(0)"

      # ------- Eğer artefakt gerekirse bu adımı açın ve 'path:' değerini ayarlayın -------
      #- name: Upload build artifacts
      #  if: always()
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: matlab-artifacts
      #    path: <ÇIKTI_KLASÖRÜ>/  # Örneğin: build/output/
