# .github/workflows/ci-windows.yml
name: Simple MATLAB CI on Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  matlab-test:
    runs-on: windows-latest

    steps:
      # 1. Depoyu çek
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. MATLAB betiğini çalıştır
      - name: Run MATLAB script
        shell: pwsh
        run: |
          # Örnek: yalnızca Hello world
          matlab -batch "disp('Hello from MATLAB on Windows CI'); exit"
          # Veya gerçek işiniz için:
          # matlab -batch "run('buildfile.m')"

      # 3. (İsteğe bağlı) Üretilen dosyaları artefakt olarak yükle
      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: matlab-output
          path: results/


